package br.com.drwars.util;

public interface Constantes {
	Long SITUACAO_NOTICIA_PENDENTE = 1l;
	Long SITUACAO_NOTICIA_APROVADO = 2l;
	Long SITUACAO_NOTICIA_REPROVADO= 3l;
	String PERFIL_DRWARSLABS = "DRWARSLABS";
	String PERFIL_FORNECEDOR = "FORNECEDOR";
	String PERFIL_CONSUMIDOR = "CONSUMIDOR";
	String PERFIL_ADMIN = "ADMIN";
	String PERFIL_CERTIFICADOR = "CERTIFICADOR";


	Long OFERTA_SITUACAO_INICIADA=1L;
	Long OFERTA_SITUACAO_EM_ANDAMENTO=3L;
	Long OFERTA_SITUACAO_FINALIZADA=2L;

	Long OFERTA_SITUACAO_CANCELADA=4L;
	Long OFERTA_TIPO_COMPRA=1L;
	Long OFERTA_TIPO_VENDA=2L;


	//ITENS
	Long ITEM_SAZONALIDADE=3L;
	Long ITEM_LOCAL_ENTREGA=5L;
	Long ITEM_FLEXIBILIDADE=8L;
	Long ITEM_VALOR_PRODUTO=13L;
	Long ITEM_TIPO_FRETE=14L;
	Long ESTADO=15L;
	Long ITEM_VALOR_CERTIFICADO=17L;
	Long ITEM_INICIO_ENTREGA=18L;
	Long ITEM_VALOR_FRETE=19L;
	Long ITEM_FIM_ENTREGA=21L;
	Long ITEM_QUANTIDAD_CERTIFICADO=22L;


}
